In [2]:
def said(a,b=5,c=10):
    print(a)
    print(b)
    print(c)
said(c=30,a=20,b=10)

20
10
30


In [3]:
import numpy as np 
x=np.arange(51)
print(x)
y=np.arange(10,50)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [4]:
t=(4,3,1,2)
print(t)
t[0]

(4, 3, 1, 2)


4

In [5]:
d=int(input())
y=d//365
d=d%365
m=d//30
d=d%30
print(y)#year
print(m)#months
print(d)#days

496
1
4
11


In [6]:
import numpy as np
x=np.ones((5,5))
print(x)
print("0 inside")
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
0 inside
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
